{"uuid": "7919d796-a4bc-4659-b7da-0b7ea520e936", "children": ["f461950b-51c2-4bac-b065-4f537382b3d8", "367fe6a9-cdfa-437a-8a3b-069549f57480"], "befores": [{"name": "xunit_setup_class_fixture_Test_web", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"C:\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\PyCode\\SF\\test-V1.0\\testcases\\test_web.py\", line 23, in setup_class\n    self.web = WebAction()\n"}, "start": 1615688381067, "stop": 1615688381067}], "start": 1615688381067, "stop": 1615688381147}